import { t } from 'i18next';

const xAxisLabels = [
    t('CONSTANTS.MONTHS_SHORT.JAN'),
    t('CONSTANTS.MONTHS_SHORT.JAN') + '_2',
    t('CONSTANTS.MONTHS_SHORT.FEB'),
    t('CONSTANTS.MONTHS_SHORT.FEB') + '_2',
    t('CONSTANTS.MONTHS_SHORT.MAR'),
    t('CONSTANTS.MONTHS_SHORT.MAR') + '_2',
    t('CONSTANTS.MONTHS_SHORT.APR'),
    t('CONSTANTS.MONTHS_SHORT.APR') + '_2',
    t('CONSTANTS.MONTHS_SHORT.MAY'),
    t('CONSTANTS.MONTHS_SHORT.MAY') + '_2',
    t('CONSTANTS.MONTHS_SHORT.JUN'),
    t('CONSTANTS.MONTHS_SHORT.JUN') + '_2',
    t('CONSTANTS.MONTHS_SHORT.JUL'),
    t('CONSTANTS.MONTHS_SHORT.JUL') + '_2',
    t('CONSTANTS.MONTHS_SHORT.AUG'),
    t('CONSTANTS.MONTHS_SHORT.AUG') + '_2',
    t('CONSTANTS.MONTHS_SHORT.SEP'),
    t('CONSTANTS.MONTHS_SHORT.SEP') + '_2',
    t('CONSTANTS.MONTHS_SHORT.OCT'),
    t('CONSTANTS.MONTHS_SHORT.OCT') + '_2',
    t('CONSTANTS.MONTHS_SHORT.NOV'),
    t('CONSTANTS.MONTHS_SHORT.NOV') + '_2',
    t('CONSTANTS.MONTHS_SHORT.DEC'),
    t('CONSTANTS.MONTHS_SHORT.DEC') + '_2',
];

export default xAxisLabels;
